
INSERT INTO "PUBLIC"."SELLER"("ID","NAME","RATING")VALUES(1,'ABC Corp',5);

INSERT INTO "PUBLIC"."CATEGORIES"("ID","NAME","SELLER_ID")VALUES(1,'Electronics',1);
INSERT INTO "PUBLIC"."CATEGORIES"("ID","NAME","SELLER_ID")VALUES(2,'Clothes',1);
INSERT INTO "PUBLIC"."CATEGORIES"("ID","NAME","SELLER_ID")VALUES(3,'Furniture',1);
INSERT INTO "PUBLIC"."CATEGORIES"("ID","NAME","SELLER_ID")VALUES(4,'Toys',1);

INSERT INTO "PUBLIC"."PRODUCTS"("ID","NAME","DESCRIPTION","PRICE","QUANTITY","RATING","SELLER_ID","CATEGORY_ID")VALUES(1,'iPhone','iPhone12',69990,10,4,1,1);

INSERT INTO "PUBLIC"."USERS"("ID","USERNAME","EMAIL","ADDRESS_LINE1","ADDRESS_LINE2","PIN")VALUES(1,'Jay','jaykumar2192@gmail.com','Pune','MH',411015);

INSERT INTO "PUBLIC"."ORDERS"("ID","TOTAL_AMOUNT","USER_ID","PRODUCT_ID","ORDER_DATE","QUANTITY","PAYMENT_INFO","ORDER_STATUS")VALUES(1,50000,1,1,sysdate,1,'Card','Processed');

INSERT INTO "PUBLIC"."USERS_CART"("ID","USER_ID","PRODUCT_ID","QUANTITY")VALUES(1,1,1,1);